// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"grpc-microservice/common"
	"grpc-microservice/config"
	"grpc-microservice/grpc-app/protos/carts"
	carts3 "grpc-microservice/grpc-app/service/carts"
	"grpc-microservice/shared/repository/carts"
	carts2 "grpc-microservice/shared/usecase/carts"
	"grpc-microservice/shared/utils"
)

// Injectors from wire.go:

func InitializeCartsService() (__.CartsServiceServer, error) {
	v := config.NewPaths()
	configConfig := config.New(v...)
	db := config.NewMySQLConnection(configConfig)
	logger := common.NewLogger()
	cartsRepository := carts.NewCartsRepositoryImpl(db, logger)
	utility := utils.NewUtility()
	cartsUseCase := carts2.NewCartsUseCaseImpl(cartsRepository, utility, logger)
	cartsServiceServer := carts3.NewCartsService(cartsUseCase, logger)
	return cartsServiceServer, nil
}
