// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"grpc-microservice/common"
	"grpc-microservice/config"
	"grpc-microservice/middleware"
)

// Injectors from wire.go:

func InitializeJWTMiddleware() (*middleware.JWTManager, error) {
	v := config.NewPaths()
	configConfig := config.New(v...)
	configJWTEnv := config.NewJwtConfig(configConfig)
	logger := common.NewLogger()
	jwtManager := middleware.NewJWTManager(configJWTEnv, logger)
	return jwtManager, nil
}
